- setup.py
The names of the authors got concatenated because of missing commas.
> Fix authors in setup.py

- qasync/__init__.py
- qasync/_unix.py
After upgrading to Qt 5.15/PySide2 5.15.1 I noticed that the asyncio-Qt mainloop integration was completely broken - websockets stayed hanging in a connecting state, async HTTP requests never returned a response i.e. no callbacks were ever called.
Troubleshooting revealed that the `__on_read_activated` slots in `_unix.py` received a `PySide2.QtCore.QSocketDescriptor object`. Those were obviously not found in the `_fd_to_key` directory mapping, as the key expected there is the (int) file descriptor.
In the Qt documentation I found that the QSocketNotifier.activated behavior changed with Qt 5.15, whereas [previously](https://doc.qt.io/qt-5.14/qsocketnotifier.html#activated) only the `QSocketNotifier::activated(int socket)` signal existed, …
> Fix issues with Qt 5.15 where QSocketNotifier.activated became overloaded

- qasync/__init__.py
As far as I can tell, the QT_API environment variable is usually set to a lowercase string (see https://pypi.org/project/QtPy/ for example). This doesn't work with the existing code as it uses value of QT_ENV as the module name. I've added a lookup to translate from the various acceptable QT_API values to module names.
> Properly handle QT_API environment variable.

- qasync/__init__.py
In certain situations, Python is running in an environment where the event loop as already been started. For example when Python is embedded as a scripting language within another application. As such, when creating a QEventLoop, we need to be able to set __is_running to True. I added an optional argument to the constructor that lets us do this.
The value if __is_running is set only after the superclass's constructor is called, because I found a bug in asyncio's BaseEventLoop: an exception occurs during initialization if the event loop reports it is already running. I'll be submitting a patch for that to the asyncio maintainers. In the meantime, setting __is_running at the end of QEventLoop's constructor seems to work fine.
Note: This is identical to a PR I put up for asyncqt here: …
> Optional argument to QEventLoop constructor for already running loops 

- qasync/__init__.py
- tests/test_qthreadexec.py
The default worker stack size for QThreadExecutor executor on macOS is insufficient to survive the default max recursion level.
I.e. The following fails with a SIGBUS error on macOS with Python 3.7.5
```python
from qasync import QThreadExecutor
def func(a, *arg, **kwarg):
func(a, *arg, **kwarg)
with QThreadExecutor(1) as executor:
f = executor.submit(func, 1)
assert isinstance(f.exception(), RecursionError)
```
Also it is impossible to use the official numpy wheel distributions with bundled openblas (https://github.com/numpy/numpy/issues/11551) due to the default stack size.
The defaults in this PR are copied from https://github.com/python/cpython/blob/v3.9.0/Python/thread_pthread.h#L35
> Ensure sufficient stack size for worker threads

- qasync/__init__.py
Qt for Python 6 is released as the [PySide6](https://pypi.org/project/PySide6/) package. From initial testing everything works just as with PySide2.
> Add support for PySide6

- .travis.yml
This PR uses the xvfb service available in travis CI for xenial linux - instead of manually finding and starting xvfb. Ref https://docs.travis-ci.com/user/trusty-to-xenial-migration-guide#3-headless-browser-testing
See failures in Travis CI in the previous PR here - https://travis-ci.org/github/CabbageDevelopment/qasync/builds/753538279
```
$ sh -e /etc/init.d/xvfb start
sh: 0: Can't open /etc/init.d/xvfb
The command "sh -e /etc/init.d/xvfb start" failed and exited with 127 during .
```
> Use the xvfb service for xenial linux

- qasync/__init__.py
- qasync/_unix.py
- qasync/_windows.py
I noticed in some cases with a lot of async functions flying around, this logging overhead can become quite dramatic.
In the worst case I had a task taking 60 seconds drop to 15 after killing all the logging (as in removing the lines, not just disabling the logger).
So I've tackled this in two ways.
1. Using pythons lazy logging. So that if there is no handler picking up the debug messages, we have no string formatting overhead.
2. Tying the debug logging in the event loop to the built in "(set|get)_debug" state. So even with debug logging enabled, the messages from the event loop can selectively be enabled/disabled.
> Reduce logging overhead

- qasync/__init__.py
Fixes #28, fixes #27.
In Python 3.9, selector_events.py stopped internally using the
`add_writer()` and `remove_writer()` public class interface, instead
calling `_add_writer()` and `_remove_writer()`. This was broken upstream
in https://github.com/python/cpython/commit/3a2667d91e3
This meant the `_remove_writer()` call was never unregistering the
QSocketNotifier, as qasync does not override that method. Rather than
crash, the write callback was simply ignoring the duplicate calls,
resulting in 100% CPU.
Cope with this by overriding the internal method names instead. This
looks like it will work at least as far back as Python 3.6. The upstream
Python repository has broken tags somehow so I can't check back further.
> Catch selector remove_writer() calls in Python>=3.9

- Pipfile
- Pipfile.lock
pytest-raises is actually needed for pytest.mark.raises.
Also removed atomicwrites and pathlib2 as they appear to be unused.
> Add pytest-raises to Pipfile

- qasync/__init__.py
```
Traceback (most recent call last):
File "/src/main.py", line 67, in on_clicked
async with grpc.aio.insecure_channel('localhost:50051') as channel:
File "/usr/local/lib/python3.8/dist-packages/grpc/aio/_channel.py", line 448, in insecure_channel
return Channel(target, () if options is None else options, None,
File "/usr/local/lib/python3.8/dist-packages/grpc/aio/_channel.py", line 277, in __init__
self._channel = cygrpc.AioChannel(
File "src/python/grpcio/grpc/_cython/_cygrpc/aio/channel.pyx.pxi", line 30, in grpc._cython.cygrpc.AioChannel.__cinit__
File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 126, in grpc._cython.cygrpc.init_grpc_aio
File "src/python/grpcio/grpc/_cython/_cygrpc/aio/grpc_aio.pyx.pxi", line 130, in grpc._cython.cygrpc.init_grpc_aio
File …
```
> Fix TypeError when using qasync alongside grpc

- qasync/__init__.py
QApplication is a QCoreApplication and has the required methods
I'm using this in a headless system with asyncio mqtt and don't want to install all the QtWidget dependencies.
Signed-off-by: David Greaves <david@dgreaves.com>
> Don't depend on QtWidgets if QtCore will do

- qasync/__init__.py
- qasync/_unix.py
Consistently use `_fileno()` throughout `qasync`.
This is a follow up on #51 which missed a spot where `_fileno()` is not called.
> Consistently use _fileno() throughout

- qasync/__init__.py
This allows using the decorator to specify a return type (using PySide) `@asyncSlot(result=bool)` and/or slot name (using PyQt) `@asyncSlot(name="foo", result=bool)`.
> Pass kwargs to asyncSlot decorator.

- qasync/__init__.py
If I use a custom QApplication, the program is running incorrectly
```
class QSingleApplication(QApplication):
...
async def main(app: QSingleApplication):
def close_future(future, loop: qasync.QIOCPEventLoop):
if loop.is_running():
future.set_result(True)
loop = asyncio.get_event_loop()
future = asyncio.Future()
app.aboutToQuit.connect(functools.partial(close_future, future, loop))
mainWindow = QMainWindow()
mainWindow.show()
return await future
if __name__ == '__main__':
try:
app = QSingleApplication()
qasync.run(main(app))
except Exception as err:
print(f'Exception:{err=}')
sys.exit(0)
```
**Error**
```
RuntimeError('Please destroy the QSingleApplication singleton before creating a new QApplication instance.')
```
> Custom QApplication  Error

- qasync/__init__.py
- tests/test_qeventloop.py
Qt ignores trailing args from a signal but python does not so inspect the slot signature and if it's not callable try removing args until it is.
In the test case below without the patch the error I get is:
```
Traceback (most recent call last):
File "/home/david/venv-heating-jan23/lib/python3.9/site-packages/qasync/__init__.py", line 789, in wrapper
task = asyncio.ensure_future(fn(*args, **kwargs))
TypeError: myaslot() takes 1 positional argument but 2 were given
```
I'm not sure if this is the best way to solve the problem as I don't think the slot code is handled in python in Pyside.
I don't have a Pyside6 environment to test with.
```[python3]
#!/usr/bin/env python3
import asyncio
import sys
import qasync
from PySide2.QtCore import QObject, QCoreApplication, QTimer, Signal, Slot
class …
```
> Allow asyncSlot slots to accept signals with mismatched signatures

- .github/workflows/test.yml
- .pre-commit-config.yaml
- README.md
- tests/test_qeventloop.py
- Python 3.6 is not available in ubuntu-latest (22.04 LTS)
- Fix tests that required `asyncio.get_running_loop()` which is not available in python 3.6
- Switched to `coactions/setup-xvfb@v1` from deprecacted `GabrielBB/xvfb-action@v1.6`
- Exclude matrix for python3.6, windows-latest, pyqt6 as it is attempting to build Qt from source
- Explicit black version for pre-commit checks
> Fix test workflow, pinned to ubuntu-20.04 instead of latest.

- qasync/__init__.py
Use hasattr() to determine how to run the app instead of a try/except-clause. Without this change, exceptions inside the app always begin with a confusing error from the try-block in qasync:
> Avoid running app.exec() inside except block

- qasync/__init__.py
`QEventLoop`s previously set themselves as the running loop by default on construction, regardless of if they are actually running or not. For `already_running` loops, this is fine, but for non-`already_running` loops, this setting of the running loop is premature.
This is because `asyncio` may check for an existing running loop after it constructs a new `QEventLoop`, but before running it. If it does, it will falsely detect the newly constructed, never ran loop as the "running" loop.
This didn't happen until Python 3.11, where `asyncio.run` checks for a running loop both before and after getting a new `QEventLoop` with the use of the new `asyncio.Runner.run`, hence raising a `RuntimeError`.
Set `QEventLoop`s as the running loop on construction exclusively when they are already running. …
> Fix qasync.run in Python 3.11

- qasync/_windows.py
For the same reason that recv(), send(), accept() and connect()
need to acquire the lock, all the other operations need to as well.
This also shows a design limitation in this approach w.r.t.
maintainability (silent failure when new operations are added);
it would be preferable to either reproduce the windows_events
implementation in its entirety, or use proxying via composition
to ensure methods not made thread-safe cannot be invoked.
Finally, the _poll implementation seems to have further issues:
it is not clear to me that the _stopped_serving handling is
thread-safe,  _unregistered is not handled, and it seems
preferable not to hold the lock when calling
GetQueuedCompletionStatus. I restricted this pull request to
addressing the straight-forward omission of wrappers for
ease of review, …
> _IocpProactor: Acquire lock in previously missed methods

- README.md
- examples/aiohttp_fetch.py
- examples/executor_example.py
- examples/qml_httpx/app.py
- examples/qml_httpx/qml/Main.qml
- examples/qml_httpx/qml/Page.qml
- examples/qml_httpx/service.py
- tests/test_qeventloop.py
This PR improves the example from various aspects.
- Organize imports and variable names with the Ruff formatter.
- Fix `aiohttp.ClientSession()` error saying that it should be run in an async function.
- Upgrade to `PySide6` and `PyQt6`.
- Use `asyncio.Event` instead of `CancelledError` exception to close the app gracefully.
- Use `PySide6.QApplication`. This is important because this class allows various font, theme, behavior setup. With `QApplication.instance`, app customization is not possible.
- Remove unnecessary details
And of course, I confirmed that this code works properly.
> Improve examples and README

- qasync/__init__.py
- tests/test_qeventloop.py
This PR resolves an issue encountered in #100 by adding functionality for logging slow `handle._run` invocations the same way it's done by `asyncio.BaseEventLoop(events.AbstractEventLoop)`.
It the modifies `_SimpleTimer.timerEvent` function by adding handle invocation time tracking in case debug mode is enabled, tightly  mimicking the code from `asyncio.base_events`.
Results of this change can be compared by running the following code:
1.1. asyncio plain code
```python
import asyncio
import time
async def main():
time.sleep(1)  # Block event loop
if __name__ == "__main__":
loop = asyncio.get_event_loop()
loop.set_debug(True)  # Enable debug
loop.slow_callback_duration = 0.1
loop.run_until_complete(main())
```
1.2. asyncio plain result
```logs
Executing <Task finished name='Task-1' …
```
> Add slow_callback_duration logging

- tests/conftest.py
- tests/test_qeventloop.py
Even though asyncio `run_forever()` returns `None`, historically, since quamash qasync returns QApplication exit code. This adds a test for that, as well as testing `run_until_complete()` returning future result as per asyncio docs.
> Test run_forever and run_until_complete return values

- examples/modal_example.py
- qasync/__init__.py
- tests/test_qeventloop.py
This pr introduces a helper, `call_sync`, to call a synchronous method via the Qt event loop.
This is useful to use from asynchronous methods, for example to invoke modal dialogue boxes via the `.exec()` method.
If this is invoked directly from an async method, it can cause task re-entrancy in the asyncio scheduler.
By using `call_sync`, the re-entrant event loop call is done from the event loop itself with no actually running task in the scheduler.
the name `call_sync` is just a suggestion, happy to change it.
If this is not a good addition, then at least we could have a similar **example** to show how to achieve this.
> New `asyncWrap` helper to execute blocking calls on the native Qt event loop

- src/qasync/_windows.py
This solves https://github.com/CabbageDevelopment/qasync/issues/128
> Use threading.Lock instead of QMutex to workaround QMutexLocker bug in PyQt6

- src/qasync/__init__.py
- src/qasync/_unix.py
- src/qasync/_windows.py
- tests/test_qeventloop.py
Runnint the unittests with PySide is sometimes prone to crashing (see #154)
This PR fixes the issues by making lifetime management more robust.
- Timer and signaller objects are parented to the `app`, for lifetime management.
- QSocketNotifiers are also parented to the `app` for lifetime management
- QEventLoop.close() is made more robust:
- The `EventPoller` is stopped.
- objects get a `.deleteLater()` for tidyness in case the __app lives on
- disconnect() calls are guarded against errors due to different bindings.
> Robustify pyside
